name: Build Android APK & Share QA Team  # Name Of Action
on: # It will Trigger ON
  push: # Every Pushes code in 
    branches: [ master ]  # Master Branch
  pull_request: # Every Pull Request  in
    branches: [ master ]  # Master Branch

jobs: # The Things is What will do when pusha and pull trigger
  build: # build APk
    runs-on: ubuntu-latest # Runs on Ubuntu Machine based on requirement like ios app works on only Macos
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
      - name: Setup JDK
        uses: actions/setup-java@v3.12.0
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build With Gradle
        run: ./gradlew clean assembleDebug
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.5.1
        with: 
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: group-of-killer-developers
          file: app/build/outputs/apk/debug/app-debug.apk
  notify:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification  # To Send Message on Discord Server
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/1146757218407034901/_FSynnoANNcCuuxZIykkfHaTMjSBhs3o54LOjZrzCprtZkSmxzAtwgH9xnE6mfhC-S5S
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'