name: Build Android APK & Share QA Team  # Name Of Action
on:  # It will Trigger ON
  push: # Every Pushes code in 
    branches: [master]  # Master Branch
  pull_request:  # Every Pull Request  in 
    branches: [master]  # Master Branch

jobs:  # The Things is What will do when pusha and pull trigger 
  build:  # build APk
    runs-on: ubuntu-latest # Runs on Ubuntu Machine based on requirement like ios app works on only Macos
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
      - name: Setup JDK
        uses: actions/setup-java@v3.12.0
        with: 
          java-version: '11'
          distribution: 'temurin'
      - name: Build With Gradle 
        run: ./gradlew clean assembleDebug
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
          
